version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./env/web.env
    volumes:
      - ./env/web.env:/app/.env:ro
      - ./public:/app/public:ro
    depends_on:
      - api
    networks:
      - fincorp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - ./env/api.env
    volumes:
      - ./env/api.env:/app/.env:ro
      - ./web/reports:/app/reports:ro
      - ./web/config:/app/config:ro
      - ./web/logs:/app/logs:ro
    networks:
      - fincorp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  fincorp-network:
    driver: bridge
    name: fincorp-ctf-network
